### ISSUE TITLE
please provide demo or screen shots

### ISSUE THREAD

**Issue by abuassar** [ngneat/dialog#1]
## I'm submitting a...
I want to see how it looks like before installing

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
the readme doesn't show how it looks like, or how it behaves.

## Expected behavior
some gifs or a demo page to show the expected UI/UX

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
https://ngneat.github.io/dialog/
