### ISSUE TITLE
Passing data to modal component displays undefined

### ISSUE THREAD

**Issue by zigax1** [ngneat/dialog#100]
## I'm submitting a

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have trouble passing data to modal dialog component.. When I want to pass data to the modal dialog, it displays undefined

'parent' component, in which I trigger a modal dialog component code is:
```
export class AdminPanelComponent implements OnInit {
  title = 'test';
  constructor(private dialog: DialogService) {}

  ngOnInit() {}

  open(passedData: any) {
    const dialogRef = this.dialog.open(EditUserComponent, {
      data: {
        title: this.title,
      },
    });
  }
}
```

Modal dialog component code is:

```
import { Component, Inject, Injectable, OnInit } from '@angular/core';
import { DialogService, DialogRef } from '@ngneat/dialog';

@Component({
  selector: 'app-edit-user',
  templateUrl: './edit-user.component.html',
  styleUrls: ['./edit-user.component.scss'],
})
@Injectable({ providedIn: 'root' })
export class EditUserComponent implements OnInit {
  ref: DialogRef<any, boolean> = Inject(DialogRef);

  ngOnInit(): void {
    console.log(this.ref.data);
  }
}
```

Maybe I am mistakenly using Inject(), because if I use lower letter --> inject() I get error that inject is unknown element in Angular.

## Expected behavior

I want to display passed data in the modal dialog component

## Environment

Angular version: 15
Ngneat version: 4.0.0

Browser:
- All browsers

**Comment by milo526** [comment]
As per [the angular documentation](https://angular.io/api/core/inject) `inject` should be written with a lowercase `i`. 

Are you sure you are importing `inject` from `@angular/core`?  

<small>If someone stumbles across this at some later point, `inject()` is available from Angular version 14 onwards, but that should be alright for your case.</small>

**Comment by zigax1** [comment]
> 

That was completely my fault. The modal is working great! Thank you for the reply
