### ISSUE TITLE
Create dialogs that don't block scrolling behind backdrop

### ISSUE THREAD

**Issue by Tlepel** [ngneat/dialog#116]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Whenever a modal is opened, the overflow of the `body` will be hidden

## Expected behavior

Modals can be created that don't necessarily have to hide the overflow. If all open modals have this setting, the body shouldn't get the `overflow: hidden` property. If any of the modals doesn't have this setting, it should behave the same as before.

## What is the motivation / use case for changing the behavior?

We sometimes use the modals as an information-overlay. However, the information is an addition to the page contents of that moment. The modal backdrop helps in this case, since it disables clicks on elements on the page, but it would be beneficial if the page contents could still be scrollable.

**Comment by Tlepel** [comment]
I'm fine with giving this a try myself by the way, seems like an interesting challenge.

**Comment by netanel-utila** [comment]
You are welcome to create a PR

**Comment by netanel-utila** [comment]
Try to check the angular material dialog impl
