### ISSUE TITLE
dialog version 5.0.0 not working with latest typescript version (5.4.5)

### ISSUE THREAD

**Issue by mrs-cp** [ngneat/dialog#119]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We are getting compile errors for the ngneat/dialog when trying to update to the latest typescript (5.4.5) version:

![Bildschirmfoto 2024-04-12 um 10 31 47](https://github.com/ngneat/dialog/assets/86765707/a7ec9655-aada-49ef-a180-499ef9052933)

## Expected behavior

dialog working as perfectly as with typescript 5.3.x

## What is the motivation / use case for changing the behavior?

To avoid security warnings, we need to update our projects and their dependencies regularly. Since we love using the ngneat/dialog, it would be awesome to get a fix for this issue.

## Environment

<pre><code>
Angular version: 17.3.4

Browser:
- [x] Chrome (desktop) version 123.0.6312.107 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v20.9.0
- Platform:  Mac

Others:

</code></pre>

**Comment by GitHubish** [comment]
Same issue
