### ISSUE TITLE
Releasing the selection in the backdrop closes the dialog

### ISSUE THREAD

**Issue by rg-lahcene** [ngneat/dialog#129]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, when you select a text or anything inside the dialog and release the selection outside the dialog ( in the backdrop), this will close the dialog as it handles the release of the mouse (selection) as click event.

## Expected behavior

I expect the dialog to remain open when selecting a text and releasing the selection outside the dialog

## Minimal reproduction of the problem with instructions

this is easily reproductible in the demo site, see gif below

![chrome_X4ppo9JFBM](https://github.com/user-attachments/assets/4bd0f7a9-17d5-4dd3-8c0c-10da8914740f)
## What is the motivation / use case for changing the behavior?

This will improve vastly the user experience, many users complains that when filling a long form inside a modal, and attempting to select quicly a text ( email for example) the end up closing the form and losing the form data.

## Environment

<pre><code>
Angular version: 18.0.0

Browser:
- [x] Chrome (desktop) version 131
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 20.15  
- Platform:  Mac and Windows

Others:

</code></pre>

**Comment by rg-lahcene** [comment]
@NetanelBasal  can you acknoweledge that this is a bug and not an intended behavio? in that can I can issue a PR to fix it

**Comment by NetanelBasal** [comment]
Yes

**Comment by rg-lahcene** [comment]
@NetanelBasal  please review #130
