### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by harsh07bharvada** [ngneat/dialog#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: Not able to install completely
</code></pre>

## Current behaviour

After running "ng add @ngneat/dialog", I get the following log in the terminal:

Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Collection 
"[myfolderLocation]/node_modules/@ngneat/dialog/schematics/collection.json" cannot be resolved.
See "/private/var/folders/7s/4rg5crc90lg_6t9bmkg08zdm0000gn/T/ng-8dErTE/angular-errors.log" for further details. 

## Expected behaviour

As stated in the docs - "This command will import the DialogModule.forRoot() in your AppModule", got no change in the file

## Minimal reproduction of the problem with instructions

`ng add @ngneat/dialog`

## What is the motivation/use case for changing the behaviour?

Want to use the library for my projects!

## Environment

<pre><code>
Angular version: 11.0.4

Browser:
- [ ] Chrome (desktop) Version 87.0.4280.141 (Official Build) (x86_64)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.18.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by tonivj5** [comment]
I can confirm it, I will fix it 👍🏻
