### ISSUE TITLE
Input dialog data type

### ISSUE THREAD

**Issue by Langstra** [ngneat/dialog#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Te data option is currently of type any. This way inside the dialog component you cannot be sure the data properties are set or when opening the dialog an ide cannot help you to set the right data properties.

## Expected behavior
Have typings for the data option properties. For example something like this: https://github.com/KevCJones/ngx-simple-modal/

## What is the motivation / use case for changing the behavior?
Have more/better typing is better and prevents errors.

**Comment by NetanelBasal** [comment]
You can pass a generic that represents the `data` property:

```ts

class AddUserDialogComponent {
    constructor(private ref: DialogRef<AddUserDialogData>) {
       ref.data // AddUserDialogData
    }
}


dialog.open<AddUserDialogData>(AddUserDialogComponent, {
  data: // AddUserDialogData
})
```

**Comment by Langstra** [comment]
Thanks, that is a good solution.
