### ISSUE TITLE
Prevent page jump when opening the dialog

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/dialog#20]
When we open the dialog, we remove the page scrollbar, which causes a layout jump. 

@tonivj5 wdyt?

**Comment by tonivj5** [comment]
Could you add a repro or an example? I don't see any layout jump in https://ngneat.github.io/dialog/

**Comment by NetanelBasal** [comment]
It's happennig in the playground. Toggle the dialog and check the end of this block:

<img width="1585" alt="Screen Shot 2021-02-19 at 10 59 19" src="https://user-images.githubusercontent.com/6745730/108481966-85802100-72a1-11eb-98ef-8374bb585a3d.png">

**Comment by NetanelBasal** [comment]
Use this button to toggle it:

<img width="369" alt="Screen Shot 2021-02-19 at 11 02 03" src="https://user-images.githubusercontent.com/6745730/108482244-e7408b00-72a1-11eb-8274-0d24ac3e940d.png">

**Comment by tonivj5** [comment]
I've been looking for a solution, and it seems to be a bit harder to fix. I've checked how [ng-bootstrap does it](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/scrollbar.ts#L44-L50), it compensates the scrollbar gap adding a [synthetic right padding](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal-stack.ts#L58), simulating scrollbar is there. We could take the same approach.

Others thoughts:
- Do nothing as Angular material does (if body has scrollbar, doesn't hide it)
- Or add a class to body/html indicating dialog is opened, and let the user to add his logic if he want to hide scroll and handle reflow.

wdty @NetanelBasal?

**Comment by NetanelBasal** [comment]
I think we should follow the Angular material approach. But pay attention that it needs to behave the same: 

- Don't hide the scrollbar
- Prevent scrolling

**Comment by NetanelBasal** [comment]
@tonivj5 any progress here?
