### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by cskasun** [ngneat/dialog#21]
When I use this I got 

`ERROR in Unexpected value 'undefined' declared by the module 'DialogModule in  /node_modules/@ngneat/dialog/ngneat-dialog.d.ts'`

But this is happening only if I run ng build-prod. ng serve is working fine.

Can somebody help to resolve this?

**Comment by NetanelBasal** [comment]
Only if you can reproduce it :)

**Comment by cskasun** [comment]
@NetanelBasal 
I just followed the instructions. and used the following to build
`node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot --build-optimizer`

**Comment by hidegh** [comment]
✔️ No issues here, with angular 11.x, kendo, bootstrap, this dialog component (and by using the max_old_space_size=8192 patch).

1st time I use this, it's very close to the Kendo implementation, just cleaner and thus IMO with greater flexibility (especially if the 2 FR's will be added). @NetanelBasal you saved my time to write this. Thanx.

**Comment by cskasun** [comment]
@hidegh 
Did you check it with angular 8.2? can you please recommend at least an old version of this lib? until I do update the angular.
