### ISSUE TITLE
Cannot use FormBuilder as DI in rendered Component.

### ISSUE THREAD

**Issue by fstodulski** [ngneat/dialog#22]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Cannot use FormBuilder in rendered component via DialogService.
Getting an Error each time FormBuilder class is used in DI in component I would like to render via DialogService.

```
RROR NullInjectorError: R3InjectorError(AppModule)[FormBuilder -> FormBuilder -> FormBuilder]: 
  NullInjectorError: No provider for FormBuilder!
    at NullInjector.get (https://localhost:4200/vendor.js:61731:27)
    at R3Injector.get (https://localhost:4200/vendor.js:61898:33)
    at R3Injector.get (https://localhost:4200/vendor.js:61898:33)
    at R3Injector.get (https://localhost:4200/vendor.js:61898:33)
    at NgModuleRef$1.get (https://localhost:4200/vendor.js:75962:33)
    at Object.get (https://localhost:4200/vendor.js:75676:35)
    at lookupTokenUsingModuleInjector (https://localhost:4200/vendor.js:54013:39)
    at getOrCreateInjectable (https://localhost:4200/vendor.js:54125:12)
    at Module.ɵɵdirectiveInject (https://localhost:4200/vendor.js:65336:12)
    at NodeInjectorFactory.AddApplicationDepartmentComponent_Factory [as factory] (https://localhost:4200/features-main-main-module.js:696:336)
```

## Expected behavior

Should render Dialog with ReactiveForm in it.

## Minimal reproduction of the problem with instructions
Create a component to render with DialogService.
Add FormBuilder in DI in this component. Try to render it.

## What is the motivation / use case for changing the behavior?

I would like to be able to create a Dialog with ReactiveForms in it.

## Environment

<pre><code>
Angular CLI: 11.2.1
Node: 14.15.1
OS: darwin x64

Angular: 11.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      0.7.5
@angular/cli                    11.2.1
@nguniversal/builders           11.2.0
@nguniversal/express-engine     11.2.0
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.5

Browser:
- [x] Chrome (desktop) version 88.0.4324.192 (x86_64)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.15.1
- Platform:  Mac

Others:
</code></pre>

**Comment by rhutchison** [comment]
@fstodulski can you submit a minimal reproduction?  I am unable to reproduce.

**Comment by Maksiemens** [comment]
I have the same issue

 "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.11",
    "@angular/common": "~11.2.11",
    "@angular/compiler": "~11.2.11",
    "@angular/core": "~11.2.11",
    "@angular/forms": "~11.2.11",
    "@angular/platform-browser": "~11.2.11",
    "@angular/platform-browser-dynamic": "~11.2.11",
    "@angular/router": "~11.2.11",
    "@auth0/angular-jwt": "^5.0.2",
    "@ng-select/ng-select": "^6.1.0",
    "@ngneat/dialog": "^1.6.0",
    "@ngneat/until-destroy": "^8.0.4",
    "@ngrx/effects": "^11.1.1",
    "@ngrx/entity": "^11.1.1",
    "@ngrx/router-store": "^11.1.1",
    "@ngrx/store": "^11.1.1",
    "@ngrx/store-devtools": "^11.1.1",
    "@rxweb/reactive-form-validators": "^2.1.2",
    "@sentry/angular": "^6.3.0",
    "@sentry/tracing": "^6.3.0",
    "@sentry/browser": "^6.3.0",
    "@swimlane/ngx-datatable": "^19.0.0",
    "@uiowa/digit-only": "^2.2.3",
    "angular-mydatepicker": "^0.11.2",
    "date-fns": "^2.21.1",
    "destyle.css": "^2.0.2",
    "intl-tel-input": "^17.0.12",
    "ng-inline-svg": "^12.1.0",
    "ng-yandex-metrika": "^4.0.0",
    "ng2-tooltip-directive": "^2.9.22",
    "ngx-clipboard": "^14.0.1",
    "ngx-custom-validators": "^11.0.1",
    "ngx-drag-scroll": "^11.0.0-beta.1",
    "ngx-file-drop": "^11.1.0",
    "ngx-image-cropper": "^3.3.5",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-mask": "^11.1.5",
    "ngx-order-pipe": "^2.1.1",
    "ngx-permissions": "^8.1.1",
    "ngx-pipes": "^2.7.5",
    "ngx-quicklink": "^0.2.7",
    "ngx-quill": "^13.2.0",
    "ngx-swiper-wrapper": "^10.0.0",
    "ngx-tabset": "^2.2.0",
    "ngx-toastr": "^13.2.1",
    "ngx-valdemort": "^5.1.0",
    "ngx-virtual-scroller": "^4.0.3",
    "rxjs": "~6.6.7",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.10",
    "@angular/cli": "^11.2.10",
    "@angular/compiler-cli": "~11.2.11",
    "@angular/language-service": "~11.2.11",
    "@ngrx/schematics": "^11.1.1",
    "@types/jasmine": "~3.6.9",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.14.41",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.0",
    "protractor": "~7.0.0",
    "rimraf": "^3.0.2",
    "stylelint": "^13.12.0",
    "stylelint-order": "^4.1.0",
    "stylelint-selector-bem-pattern": "^2.1.0",
    "svg2sprite-cli": "^2.0.1",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.3",
    "typescript": "~4.1.5",
    "webpack-bundle-analyzer": "^4.4.1"
  }

**Comment by hidegh** [comment]
✔️ **I don't have issues injecting FormBuilder** - works as expected (not as if I'd use that Form builder - as Angular template based approach just lacks a good validation component and some extra code around to achieve great and flexible validation without data pull-push codes)...

Here's something that I put together (and what the Angular team should have) to dynamically render errors from an error function (or from API result) which uses just an array of error objects...
![angular - custom 3rd party validation - test page](https://user-images.githubusercontent.com/6331063/118161710-2f45f880-b420-11eb-8e52-3f299ff54fe2.png)

**Comment by adisreyaj** [comment]
Facing the same issue. All the modules needs to be imported in the `app.module.ts` to solve the errors. Any update or workaround available for this?

**Comment by NetanelBasal** [comment]
FormBuilder is now available in the root.

https://github.com/angular/angular/commit/02691a74bb9889bae42f1c1c37b70c946f322dd5
