### ISSUE TITLE
Close dialog by this.dialog.closeAll()

### ISSUE THREAD

**Issue by Maksiemens** [ngneat/dialog#23]
Could U do something same in angular material like private dialog: MatDialog, this.dialog.closeAll();
This will help wnen I work with ngrx and with success action I have to close dialog
Thank You
For example with angular material
![image](https://user-images.githubusercontent.com/26347041/109859003-276e1900-7c65-11eb-9fd2-ad5ad180a8f2.png)

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
