### ISSUE TITLE
[FR] Option to disable backdrop close, but still allow closing via ESC (if not disabled)

### ISSUE THREAD

**Issue by hidegh** [ngneat/dialog#34]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Setting enableClose: false also removes the ability to close the modal via ESC.

## Expected behavior
While unintended click outside the modal (on the backdrop) and a following close is in most cases undesired,
Closing when ESC is presses is smthing usually expected.

## What is the motivation / use case for changing the behavior?
Ease of use, DRY when implementing modals.

## Environment

<pre><code>
Angular version: 11.x.x

Browser:
- [x] Chrome (desktop) version - latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I'm not sure you are right, but I'm willing to get a PR that makes it configurable.

**Comment by hidegh** [comment]
@NetanelBasal typical use-case:
1. user is writing a long description into a <textarea>
2. for some reason presses ESC (unintendedly)
3. dialog closes, the written up text disappears

The idea is to still provide a way to exit dialog (cancel btn, close X btn on the header) in an easy manner, but avoid accidental closing.

**Comment by Lonli-Lokli** [comment]
@hidegh You can archieeve this in custom window with this code

```
@HostListener('window:keyup.esc')
  onEscKeyUp() {
    this.dialogRef.close();
  }
```
