### ISSUE TITLE
Problem with typescript 3.5.1 and/or angular 8.2.14

### ISSUE THREAD

**Issue by Ecekiel** [ngneat/dialog#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When im trying to compile my angular 8.2.14 app I get the following error in "node_modules/@ngneat/dialog/lib/draggable.directive.d.ts": 

An accessor cannot be declared in an ambient context.

     set dialogDragOffset(offset: DragOffset);

When deleting the "set" keyword it successfully compiles and the dialog works fine for me, but I'm not entirely sure if there are some other problems that occur when removing this keyword. 

Can't compile my angular application.

## Expected behavior

I can compile my application, with ngneat/dialog included.

I want to compile and use the ngneat/dialog in my 8.2.14 angular app. Is there any way to fix that?
The current solution is obviously not sufficient since I need it to build on a build server.

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.1  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You need to update TS

**Comment by Ecekiel** [comment]
Thank you, I updated it to 3.5.1 thinking it was the latest release I could use not seeing there are 3.5.2 and even 3.5.3.

I updated to 3.5.3 and it works now. Sorry for this stupid question/issue.

Have a nice weekend!
