### ISSUE TITLE
[FR] Able to change the default dialog buttons inner text

### ISSUE THREAD

**Issue by hamonCordova** [ngneat/dialog#47]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Default button text on dialogs (success, erro and confirm)

## Expected behavior

I would like to change the default buttons text. They current are "Cancel" and "OK".

## What is the motivation / use case for changing the behavior?

It can be better for cases witch the "Cancel" and "OK" doesn't are the beast meaning.

**Comment by NetanelBasal** [comment]
Sure, you're welcome to submit a PR.
