### ISSUE TITLE
other Popup stopped working

### ISSUE THREAD

**Issue by KannanRams** [ngneat/dialog#6]
I'm submitting a...

[x] Bug report  
[x] Support request

Current behavior

After first popup of ngneat dialog, other dialogs or popups like (datepicker) stopped working

Expected behavior

ngneat dialog should not affect other popups

Environment

Angular version: 10.0.4

Browser:
- [ x] Chrome (desktop) version 84.0.4147.125 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: 14.1.0
- Platform:  Windows

**Comment by NetanelBasal** [comment]
z-index?

**Comment by KannanRams** [comment]
Thanks for your guidance.
I don't know how to change z-index and make it work.
When I refresh / reload the app, everything works again, once I show ngneat dialog, again all other popups stopped working, also some css styles are changed for buttons, input text etc.
Thanks to assist, provide your valuable comments.
