### ISSUE TITLE
Invalid dialog id

### ISSUE THREAD

**Issue by mishahrokhola** [ngneat/dialog#63]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:

</code></pre>

## Current behavior

Randomly generates invalid dialog id with a number at the start. 
[Id specification](https://www.w3.org/TR/html4/types.html#type-id)

## Expected behavior

Should always generate an id that starts with a letter.

## Minimal reproduction of the problem with instructions

It's randomly generated so no specific steps to reproduce.

## What is the motivation/use case for changing the behavior?

If you need to query dialog by id from the DOM (more than 1 dialog is opened).

<img width="610" alt="image" src="https://user-images.githubusercontent.com/29478275/169951137-0a8d77d8-69b2-4903-a316-5de453111027.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/29478275/169951172-4e48fef8-bfe0-4360-a955-dee2bdcc3d05.png">

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR
