### ISSUE TITLE
Dragging only moves handle, leaves dialog behind

### ISSUE THREAD

**Issue by jemand771** [ngneat/dialog#84]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When trying to drag the drag handle ("marker") of a dialog, only the handle itself moves.

## Expected behavior

The whole dialog moves as it did before

## Minimal reproduction of the problem with instructions

1. clone this repo (the playground)
2. `npm ci && npm run start`
3. create a dialog with `draggable: true`
4. (optional) apply custom style to the drag handle to make it easier to see
5. try to drag the dialog

alternatively, the same behaviour is reproducible over on https://ngneat.github.io/dialog/
you can use your browser's css inspector to add something like this to make the issue more visible:
```css
.ngneat-drag-marker {
    background: red;
}
```
![chrome_3CJw0oCXDy](https://user-images.githubusercontent.com/19669567/211841098-70ced47d-89b6-4cc3-ae57-2d1827af1148.gif)

## Environment

<pre><code>
Angular version: 15.0.0, 15.0.4 (almost latest)

Browser:
- [x] Chrome (desktop) version 108
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 108
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 108
 

Others:
* I noticed the regression in a local project after upgrading from 2.1.1 to 3.3.0
* I was able to reproduce it in the latest playground (1d5509210d124d65c1cf15c7ee84951dfe1cde2c) aswell as 3.0.0 (028bccadd8275ef8966ff0921894c9fd32a12e9a)
* it's weird how the latest release commit on github is 3.1.0, but npm has 3.3.0 already. I didn't look into that any further and hope my version info is correct
</code></pre>

**Comment by NetanelBasal** [comment]
I see. I'll check when I find some free time. It'll be great if you can help and at least check in which commit it was broken.

**Comment by jemand771** [comment]
sure! I had some trouble getting the older versions to build at first, but I got it in the end.

looks like it's f5575f59da2fb61b9c0aa229e8890eaf32a2a56c, because it's broken there while 5a1fd12c66a3e817b879eaf4afb6952d71102b71 is still fine

**Comment by ccondrup** [comment]
> alternatively, the same behaviour is reproducible over on https://ngneat.github.io/dialog/

Was the demo website ever updated with the fix? I am still seeing the faulty behaviour there. Not the best impression if you're looking for a draggable dialog and coming here checking the demo first.
